---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age173xt5e5ftz9gh8av7ugtdv5m7cudzktjndfcdjh85h33j9sc939qlgy95f
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age173xt5e5ftz9gh8av7ugtdv5m7cudzktjndfcdjh85h33j9sc939qlgy95f
