# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:5Ji883IZspr/sBQK,iv:1O15oq6IAnNq65K6M7mXqvg41cAguC966bMpnGW0lOc=,tag:RNrXv0Oe0s9LsVtP4nmO8g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FJysOf7IFqJg709ugiRMxF6Zlq/6xB95NA==,iv:eVFPp8jHwgisuqaCUCxRev6BbmtcC4jNtGslEmXPmU4=,tag:p4Vyr4o9P9YIktkiJT/TMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age173xt5e5ftz9gh8av7ugtdv5m7cudzktjndfcdjh85h33j9sc939qlgy95f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdG8yVXhYU0VZRjFyeUZX
            eFFmQThyTERXdHlYYnUvS2FaZkxhRE1vKzBnCm9uSnpxWkFQUGR6NTUyVklmOHZH
            ejEvQjBzWlVqRUY1UEpkbmRUSHNsUncKLS0tIFRWZ1BNMWk4MnFyMEVENlcxZnV5
            TklEcGIxYWFXZWI4dXh1b1FuZ2h4aDgKUoZH6ERIN7S1Jh4yKOuL2T2iIRPumVX3
            i+IGmqH/b3SaKCwxl2UXoql4TdG1w+2GcAR5i8vfXqn/vWNqzm443w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-15T21:42:45Z"
    mac: ENC[AES256_GCM,data:COgDW0iYmiGMkf4eq+SSDLpLaTpcZz5DIeX5ybZHbh4strPDn9/Myn7F48kreC+FiFvrcjf3UXe18Sdu4gHyHAQH7FkEKTWAcaCGElPF8Rlx9lhRYu174h4ll/U3BrymkMLkk3CBmeReZq9LFduA1D04I4uRMfOlY7OI/hKVZrE=,iv:bVUEQDtTNQQ+2jw6CWVNQAEhGl8xsX3ky3HWEoVz7yg=,tag:TdqB5zi7cJnexn5nbCUMHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
