# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:WmbA/LsGmqrr7/P9uQDDdBocGbwSHK/RIdmvt+d1Vg6QJidtvQ==,iv:7mu4Q41sSWFoet55r1hH5y6LjVBW0KV6TXSEpi9/Bz4=,tag:FaxgWwB/kWWaS6Ag4Y7zdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age173xt5e5ftz9gh8av7ugtdv5m7cudzktjndfcdjh85h33j9sc939qlgy95f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NURRc1ljVytZTnU3bXJk
            ZTBvd2FLWFY1eHdFcnEzQU1uZ253TXR2amk0CjF4VWlBVXBMaDNOTUZDTnR1c3dK
            T2NYbG1Vb3ZrQW13WkthckVYOWZXT3MKLS0tIFdlL2Eyd2xQWnptVjR6RVpOSW01
            dHpyR24xT1ZLR21WRmVKRTNrOWtzcW8KgKQ2kgwdfIaVrqqmQGruLOTGkS2yU4pR
            0/H1R1ukGSF5LQN/Ola16aHhFQ9oO4ezR4B9EcdWKbOg6c8tL9eKpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-15T21:42:45Z"
    mac: ENC[AES256_GCM,data:QchEURvGUfRvAoum74hV/F2bGR1/DrolMswbptUVGpWPl20LkOtaJ1oNqfjsb2UUn3HWn8WJHrar8D+PFupbxm5x+PmXf7nXHdcJBG06PIXlKl/1S4yV0Poq3khhk5ecSoIxH2CefnOR2TxnyaFtItb6l7R+VBAetM9yYKqjb0Q=,iv:1RoV9NcsCup0wR9DQo0UqHggj5BUb4cCEM2DAP2Riss=,tag:OULO01QV9I47/njJZWHrxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
